### ISSUE TITLE
ISO 8601 duration parsing error

### ISSUE THREAD

**Issue by aliismayilov** [pawurb/pg-locks-monitor#5]
Continuing to test on production 😅 I get the following error:
```ruby
{
    "name": "ActiveSupport::Duration::ISO8601Parser::ParsingError",
    "message": "Invalid ISO 8601 duration: \"00:00:00.002304\"",
    "stack_trace": [
        "/vendor/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/duration/iso8601_parser.rb:97:in `raise_parsing_error'",
        "/vendor/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/duration/iso8601_parser.rb:56:in `parse!'",
        "/vendor/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/duration.rb:145:in `parse'",
        "/vendor/ruby/3.3.0/gems/pg-locks-monitor-0.2.1/lib/pg-locks-monitor.rb:12:in `block in snapshot!'",
        "/vendor/ruby/3.3.0/gems/pg-locks-monitor-0.2.1/lib/pg-locks-monitor.rb:10:in `select'",
        "/vendor/ruby/3.3.0/gems/pg-locks-monitor-0.2.1/lib/pg-locks-monitor.rb:10:in `snapshot!'",
        "/app/app/workers/pg_locks_monitoring_worker.rb:12:in `perform'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:220:in `execute_job'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:185:in `block (4 levels) in process'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:180:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/app/lib/sidekiq/middleware/server/active_support_notification.rb:12:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/app/lib/sidekiq/middleware/server/set_worker_job_retry_count.rb:16:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/app/lib/sidekiq/middleware/server/set_audit_log_context.rb:11:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/app/lib/sidekiq/middleware/server/active_storage_error_handler.rb:8:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/app/lib/sidekiq/middleware/server/log_arguments.rb:16:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-pro-7.3.1/lib/sidekiq/batch/middleware.rb:58:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-ent-7.3.1/lib/sidekiq-ent/unique.rb:184:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-ent-7.3.1/lib/sidekiq-ent/limiter/middleware.rb:10:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job/interrupt_handler.rb:9:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/metrics/tracking.rb:26:in `track'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/metrics/tracking.rb:134:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'",
        "/vendor/ruby/3.3.0/gems/appsignal-4.0.9/lib/appsignal/transaction.rb:579:in `instrument'",
        "/vendor/ruby/3.3.0/gems/appsignal-4.0.9/lib/appsignal/helpers/instrumentation.rb:747:in `instrument'",
        "/vendor/ruby/3.3.0/gems/appsignal-4.0.9/lib/appsignal/integrations/sidekiq.rb:70:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:182:in `traverse'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/middleware/chain.rb:173:in `invoke'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:184:in `block (3 levels) in process'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:145:in `block (6 levels) in dispatch'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job_retry.rb:118:in `local'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:144:in `block (5 levels) in dispatch'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/rails.rb:16:in `block in call'",
        "/vendor/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/reloader.rb:77:in `block in wrap'",
        "/vendor/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/execution_wrapper.rb:91:in `wrap'",
        "/vendor/ruby/3.3.0/gems/activesupport-7.2.1/lib/active_support/reloader.rb:74:in `wrap'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/rails.rb:15:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:139:in `block (4 levels) in dispatch'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:281:in `stats'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:134:in `block (3 levels) in dispatch'",
        "/vendor/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/base.rb:375:in `measure_internal'",
        "/vendor/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/base.rb:97:in `measure_info'",
        "/vendor/ruby/3.3.0/gems/rails_semantic_logger-4.17.0/lib/rails_semantic_logger/sidekiq/job_logger.rb:21:in `block in call'",
        "/vendor/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/semantic_logger.rb:395:in `named_tagged'",
        "/vendor/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/semantic_logger.rb:351:in `tagged'",
        "/vendor/ruby/3.3.0/gems/rails_semantic_logger-4.17.0/lib/rails_semantic_logger/sidekiq/job_logger.rb:12:in `call'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:133:in `block (2 levels) in dispatch'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/job_retry.rb:85:in `global'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:132:in `block in dispatch'",
        "/vendor/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/semantic_logger.rb:395:in `named_tagged'",
        "/vendor/ruby/3.3.0/gems/semantic_logger-4.16.0/lib/semantic_logger/semantic_logger.rb:351:in `tagged'",
        "/vendor/ruby/3.3.0/gems/rails_semantic_logger-4.17.0/lib/rails_semantic_logger/sidekiq/job_logger.rb:38:in `prepare'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:131:in `dispatch'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:183:in `block (2 levels) in process'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:182:in `handle_interrupt'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:182:in `block in process'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:181:in `handle_interrupt'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:181:in `process'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:86:in `process_one'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/processor.rb:76:in `run'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/component.rb:10:in `watchdog'",
        "/vendor/ruby/3.3.0/gems/sidekiq-7.3.2/lib/sidekiq/component.rb:19:in `block in safe_thread'"
    ]
}
```

Seems like [this line](https://github.com/pawurb/pg-locks-monitor/blob/v0.2.1/lib/pg-locks-monitor.rb#L11) receives `00:00:00.098276` and it cannot parse it as ActiveSupport Duration.

Let me know please if I can provide more information.

**Comment by pawurb** [comment]
@aliismayilov this is the way 😄 please try `0.3.0`
